<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $users = [
            // ── Practitioners ──────────────────────────────────────────────
            [
                'id'               => 'p_sarah',
                'role'             => 'practitioner',
                'display_name'     => 'Sarah Johnson',
                'credentials'      => 'LPC, LMFT',
                'email'            => 'sarah@demo.aegis',
                'phone'            => '555-201-0001',
                'location'         => 'Austin, TX',
                'organization'     => 'Clarity Counseling Group',
                'avatar_initials'  => 'SJ',
                'title'            => 'Licensed Professional Counselor',
                'specialty'        => 'Trauma & Anxiety',
                'bio'              => 'Experienced therapist specializing in trauma-informed care, anxiety, and life transitions.',
                'slug'             => 'sarah-johnson-lpc',
                'practitioner_public' => 1,
                'tier'             => 'practice',
                'services_mode'    => 1,
                'maat_addon'       => 1,
                'two_factor_enabled' => 0,
                'verified'         => 1,
                'stripe_connected'         => 1,
                'stripe_account_id'        => 'acct_demo_sarah',
                'stripe_id'                => 'cus_demo_sarah',
                'stripe_payment_method_id' => 'pm_demo_visa_sarah',
                'last_login_at'    => $now->copy()->subHours(2),
                'created_at'       => $now->copy()->subMonths(8),
                'updated_at'       => $now->copy()->subHours(2),
            ],
            [
                // ── p_rehan — Rehan Rashid, same tier as p_sarah, real Gmail for testing
                'id'               => 'p_rehan',
                'role'             => 'practitioner',
                'display_name'     => 'Rehan Rashid',
                'credentials'      => 'LPC, LMFT',
                'email'            => 'rehanthewebbee@gmail.com',
                'phone'            => '555-201-9999',
                'location'         => 'Austin, TX',
                'organization'     => 'Clarity Counseling Group',
                'avatar_initials'  => 'RR',
                'title'            => 'Licensed Professional Counselor',
                'specialty'        => 'Trauma & Anxiety',
                'bio'              => 'Experienced therapist specializing in trauma-informed care, anxiety, and life transitions.',
                'slug'             => 'rehan-rashid-lpc',
                'practitioner_public' => 1,
                'tier'             => 'practice',
                'services_mode'    => 1,
                'maat_addon'       => 1,
                'two_factor_enabled' => 0,
                'verified'         => 1,
                'stripe_connected'         => 1,
                'stripe_account_id'        => 'acct_demo_sarah',
                'stripe_id'                => 'cus_demo_rehan',
                'stripe_payment_method_id' => 'pm_demo_visa_rehan',
                'last_login_at'    => $now->copy()->subHours(1),
                'created_at'       => $now->copy()->subMonths(8),
                'updated_at'       => $now->copy()->subHours(1),
            ],

            [
                'id'               => 'p_david',
                'role'             => 'practitioner',
                'display_name'     => 'David Chen',
                'credentials'      => 'LCSW',
                'email'            => 'david@demo.aegis',
                'phone'            => '555-201-0002',
                'location'         => 'Seattle, WA',
                'organization'     => null,
                'avatar_initials'  => 'DC',
                'title'            => 'Licensed Clinical Social Worker',
                'specialty'        => 'Depression & Mood Disorders',
                'bio'              => 'Providing evidence-based care for depression and mood disorders.',
                'slug'             => 'david-chen-lcsw',
                'practitioner_public' => 1,
                'tier'             => 'access',
                'services_mode'    => 0,
                'stripe_connected'         => 1,
                'stripe_account_id'        => 'acct_demo_david',
                'stripe_id'                => 'cus_demo_david',
                'stripe_payment_method_id' => 'pm_demo_visa_david',
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subDays(1),
                'created_at'       => $now->copy()->subMonths(4),
                'updated_at'       => $now->copy()->subDays(1),
            ],
            [
                'id'               => 'p_maria',
                'role'             => 'practitioner',
                'display_name'     => 'Maria Santos',
                'credentials'      => 'PhD, LMFT',
                'email'            => 'maria@demo.aegis',
                'phone'            => '555-201-0003',
                'location'         => 'Miami, FL',
                'organization'     => 'Santos Integrative Wellness',
                'avatar_initials'  => 'MS',
                'title'            => 'Licensed Marriage and Family Therapist',
                'specialty'        => 'Couples & Family Systems',
                'bio'              => 'Integrative therapist working with couples, families, and individuals navigating relational dynamics.',
                'slug'             => 'maria-santos-phd',
                'practitioner_public' => 1,
                'tier'             => 'practice',
                'services_mode'    => 1,
                'maat_addon'       => 1,
                'two_factor_enabled' => 0,
                'verified'         => 1,
                'stripe_connected'         => 1,
                'stripe_account_id'        => 'acct_demo_maria',
                'stripe_id'                => 'cus_demo_maria',
                'stripe_payment_method_id' => 'pm_demo_visa_maria',
                'last_login_at'    => $now->copy()->subHours(5),
                'created_at'       => $now->copy()->subMonths(6),
                'updated_at'       => $now->copy()->subHours(5),
            ],
            [
                'id'               => 'p_access_only',
                'role'             => 'practitioner',
                'display_name'     => 'Jordan Lee',
                'credentials'      => 'LMHC',
                'email'            => 'jordan@demo.aegis',
                'phone'            => '555-201-0010',
                'location'         => 'Portland, OR',
                'avatar_initials'  => 'JL',
                'title'            => 'Licensed Mental Health Counselor',
                'specialty'        => 'Adolescent & Young Adult',
                'slug'             => 'jordan-lee-lmhc',
                'practitioner_public' => 1,
                'tier'             => 'access',
                'verified'         => 0,
                'last_login_at'    => $now->copy()->subDays(3),
                'created_at'       => $now->copy()->subWeeks(2),
                'updated_at'       => $now->copy()->subDays(3),
            ],
            [
                'id'               => 'p_locked',
                'role'             => 'practitioner',
                'display_name'     => 'Alex Reed',
                'credentials'      => 'LPCC',
                'email'            => 'alex@demo.aegis',
                'phone'            => '555-201-0011',
                'location'         => 'Denver, CO',
                'avatar_initials'  => 'AR',
                'title'            => 'Licensed Professional Clinical Counselor',
                'specialty'        => 'Substance Use',
                'slug'             => 'alex-reed-lpcc',
                'practitioner_public' => 0,
                'tier'             => 'access',
                'locked_at'        => $now->copy()->subDays(2),
                'locked_reason'    => 'Multiple failed login attempts',
                'failed_login_count' => 5,
                'last_login_at'    => null,
                'created_at'       => $now->copy()->subMonths(2),
                'updated_at'       => $now->copy()->subDays(2),
            ],
            [
                'id'               => 'p_deactivated',
                'role'             => 'practitioner',
                'display_name'     => 'Sam Park',
                'credentials'      => 'PsyD',
                'email'            => 'sam@demo.aegis',
                'phone'            => '555-201-0012',
                'location'         => 'Chicago, IL',
                'avatar_initials'  => 'SP',
                'title'            => 'Doctor of Psychology',
                'specialty'        => 'Neuropsychology',
                'slug'             => 'sam-park-psyd',
                'practitioner_public' => 0,
                'tier'             => 'practice',
                'deactivated_at'   => $now->copy()->subDays(30),
                'last_login_at'    => $now->copy()->subDays(32),
                'created_at'       => $now->copy()->subMonths(10),
                'updated_at'       => $now->copy()->subDays(30),
            ],

            // ── Continuity Stewards ────────────────────────────────────────
            [
                'id'               => 'cs_marcus',
                'role'             => 'continuity_steward',
                'display_name'     => 'Marcus Williams',
                'credentials'      => 'MSW, LICSW',
                'email'            => 'marcus@demo.aegis',
                'phone'            => '555-202-0001',
                'location'         => 'Austin, TX',
                'organization'     => 'Williams Continuity Services',
                'avatar_initials'  => 'MW',
                'title'            => 'Licensed Independent Clinical Social Worker',
                'specialty'        => 'Continuity Planning',
                'slug'             => 'marcus-williams-licsw',
                'cs_public'        => 1,
                'cs_account_type'  => 'business',
                'cs_path'          => 'business',
                'two_factor_enabled' => 1,
                'verified'         => 1,
                'stripe_connected' => 1,
                'stripe_account_id'=> 'acct_demo_marcus',
                'last_login_at'    => $now->copy()->subHours(1),
                'created_at'       => $now->copy()->subYears(1),
                'updated_at'       => $now->copy()->subHours(1),
            ],
            [
                'id'               => 'cs_priya',
                'role'             => 'continuity_steward',
                'display_name'     => 'Priya Raman',
                'credentials'      => 'LCSW, CCM',
                'email'            => 'priya@demo.aegis',
                'phone'            => '555-202-0002',
                'location'         => 'Houston, TX',
                'organization'     => 'Raman Care Coordination',
                'avatar_initials'  => 'PR',
                'title'            => 'Licensed Clinical Social Worker',
                'specialty'        => 'Care Management',
                'slug'             => 'priya-raman-lcsw',
                'cs_public'        => 1,
                'cs_account_type'  => 'business',
                'cs_path'          => 'business',
                'verified'         => 1,
                'stripe_connected' => 1,
                'stripe_account_id'=> 'acct_demo_priya',
                'last_login_at'    => $now->copy()->subHours(6),
                'created_at'       => $now->copy()->subMonths(9),
                'updated_at'       => $now->copy()->subHours(6),
            ],
            [
                'id'               => 'cs_alternate',
                'role'             => 'continuity_steward',
                'display_name'     => 'James Wilson',
                'credentials'      => 'LMFT',
                'email'            => 'jameswilson@demo.aegis',
                'phone'            => '555-202-0003',
                'location'         => 'Nashville, TN',
                'avatar_initials'  => 'JW',
                'title'            => 'Licensed Marriage and Family Therapist',
                'specialty'        => 'Family Systems',
                'slug'             => 'james-wilson-lmft',
                'cs_public'        => 0,
                'cs_account_type'  => 'invited',
                'cs_path'          => 'invited',
                'linked_provider_id' => 'p_sarah',
                'invited_by_id'    => 'p_sarah',
                'verified'         => 0,
                'last_login_at'    => $now->copy()->subDays(5),
                'created_at'       => $now->copy()->subMonths(3),
                'updated_at'       => $now->copy()->subDays(5),
            ],
            [
                'id'               => 'cs_resigned',
                'role'             => 'continuity_steward',
                'display_name'     => 'Rachel Kim',
                'credentials'      => 'LCPC',
                'email'            => 'rachelkim@demo.aegis',
                'phone'            => '555-202-0004',
                'location'         => 'Philadelphia, PA',
                'avatar_initials'  => 'RK',
                'title'            => 'Licensed Clinical Professional Counselor',
                'slug'             => 'rachel-kim-lcpc',
                'cs_public'        => 0,
                'cs_account_type'  => 'business',
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subDays(14),
                'created_at'       => $now->copy()->subMonths(7),
                'updated_at'       => $now->copy()->subDays(14),
            ],

            // ── Support Stewards ───────────────────────────────────────────
            [
                'id'               => 'ss_linda',
                'role'             => 'support_steward',
                'display_name'     => 'Linda Foster',
                'credentials'      => 'RN, MSN',
                'email'            => 'linda@demo.aegis',
                'phone'            => '555-203-0001',
                'location'         => 'Austin, TX',
                'organization'     => null,
                'avatar_initials'  => 'LF',
                'title'            => 'Registered Nurse',
                'specialty'        => 'Emergency Care',
                'slug'             => 'linda-foster-rn',
                'invited_by_id'    => 'p_sarah',
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subHours(3),
                'created_at'       => $now->copy()->subMonths(7),
                'updated_at'       => $now->copy()->subHours(3),
            ],
            [
                'id'               => 'ss_james',
                'role'             => 'support_steward',
                'display_name'     => 'James Carter',
                'credentials'      => 'EMT-P',
                'email'            => 'jamescarter@demo.aegis',
                'phone'            => '555-203-0002',
                'location'         => 'Seattle, WA',
                'avatar_initials'  => 'JC',
                'title'            => 'Paramedic',
                'slug'             => 'james-carter-emt',
                'invited_by_id'    => 'p_david',
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subDays(2),
                'created_at'       => $now->copy()->subMonths(5),
                'updated_at'       => $now->copy()->subDays(2),
            ],

            // ── Business Partners ──────────────────────────────────────────
            [
                'id'               => 'bp_acme',
                'role'             => 'business_partner',
                'display_name'     => 'Acme Health Services',
                'email'            => 'contact@acmehealth.demo.aegis',
                'phone'            => '555-204-0001',
                'location'         => 'New York, NY',
                'organization'     => 'Acme Health Services LLC',
                'avatar_initials'  => 'AH',
                'title'            => 'Healthcare Administration Services',
                'slug'             => 'acme-health-services',
                'business_partner_public' => 1,
                'bp_type'          => 'agency',
                'bp_business_name' => 'Acme Health Services LLC',
                'bp_team_size'     => 8,
                'bp_hourly_rate_cents' => 12500,
                'bp_categories'    => json_encode(['billing', 'credentialing', 'admin']),
                'verified'         => 1,
                'stripe_connected' => 1,
                'stripe_account_id'         => 'acct_demo_acme',       // Replace with real acct_ from Stripe dashboard
                'w9_status'        => 'approved',
                'last_login_at'    => $now->copy()->subHours(4),
                'created_at'       => $now->copy()->subYears(1),
                'updated_at'       => $now->copy()->subHours(4),
            ],
            [
                'id'               => 'bp_jamal',
                'role'             => 'business_partner',
                'display_name'     => 'Jamal Torres',
                'credentials'      => 'CPC',
                'email'            => 'jamal@demo.aegis',
                'phone'            => '555-204-0002',
                'location'         => 'Atlanta, GA',
                'avatar_initials'  => 'JT',
                'title'            => 'Certified Professional Coder',
                'slug'             => 'jamal-torres-cpc',
                'business_partner_public' => 1,
                'bp_type'          => 'freelancer',
                'bp_hourly_rate_cents' => 8500,
                'bp_categories'    => json_encode(['billing', 'coding']),
                'verified'         => 1,
                'stripe_connected' => 1,
                'stripe_account_id'         => 'acct_demo_jamal',      // Replace with real acct_ from Stripe dashboard
                'w9_status'        => 'approved',
                'last_login_at'    => $now->copy()->subDays(1),
                'created_at'       => $now->copy()->subMonths(6),
                'updated_at'       => $now->copy()->subDays(1),
            ],
            [
                'id'               => 'bp_team_owner',
                'role'             => 'business_partner',
                'display_name'     => 'Nexus Consulting',
                'email'            => 'contact@nexus.demo.aegis',
                'phone'            => '555-204-0003',
                'location'         => 'Chicago, IL',
                'organization'     => 'Nexus Consulting Group',
                'avatar_initials'  => 'NC',
                'title'            => 'Healthcare Operations Consultancy',
                'slug'             => 'nexus-consulting-group',
                'business_partner_public' => 1,
                'bp_type'          => 'agency',
                'bp_business_name' => 'Nexus Consulting Group',
                'bp_team_size'     => 4,
                'bp_hourly_rate_cents' => 15000,
                'bp_categories'    => json_encode(['consulting', 'admin', 'credentialing']),
                'verified'         => 1,
                'stripe_connected' => 1,
                'stripe_account_id'=> 'acct_demo_nexus',
                'w9_status'        => 'approved',
                'last_login_at'    => $now->copy()->subDays(2),
                'created_at'       => $now->copy()->subMonths(5),
                'updated_at'       => $now->copy()->subDays(2),
            ],
            [
                'id'               => 'bp_team_member',
                'role'             => 'business_partner',
                'display_name'     => 'Tanya Brooks',
                'email'            => 'tanya@demo.aegis',
                'phone'            => '555-204-0004',
                'location'         => 'Chicago, IL',
                'avatar_initials'  => 'TB',
                'title'            => 'Healthcare Operations Specialist',
                'slug'             => 'tanya-brooks',
                'business_partner_public' => 0,
                'bp_type'          => 'freelancer',
                'bp_hourly_rate_cents' => 9000,
                'bp_categories'    => json_encode(['admin', 'scheduling']),
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subDays(1),
                'created_at'       => $now->copy()->subMonths(4),
                'updated_at'       => $now->copy()->subDays(1),
            ],

            // ── Admin ──────────────────────────────────────────────────────
            [
                'id'               => 'admin_root',
                'role'             => 'admin',
                'display_name'     => 'Aegis Admin',
                'email'            => 'admin@aegis.internal',
                'phone'            => '555-900-0001',
                'avatar_initials'  => 'AA',
                'title'            => 'Platform Administrator',
                'slug'             => 'aegis-admin',
                'two_factor_enabled' => 1,
                'verified'         => 1,
                'last_login_at'    => $now->copy()->subMinutes(30),
                'created_at'       => $now->copy()->subYears(2),
                'updated_at'       => $now->copy()->subMinutes(30),
            ],
        ];

        foreach ($users as $user) {
            // Set defaults for nullable columns not explicitly set
            $user = array_merge([
                'password'              => Hash::make('Demo1234!'),
                'credentials'           => null,
                'phone'                 => null,
                'location'              => null,
                'organization'          => null,
                'avatar_initials'       => null,
                'title'                 => null,
                'specialty'             => null,
                'bio'                   => null,
                'slug'                  => null,
                'slug_locked_at'        => null,
                'practitioner_public'   => 0,
                'cs_public'             => 0,
                'business_partner_public' => 0,
                'tier'                  => null,
                'services_mode'         => 0,
                'maat_addon'            => 0,
                'payment_model'         => null,
                'cs_account_type'       => null,
                'cs_path'               => null,
                'linked_provider_id'    => null,
                'stripe_connected'      => 0,
                'stripe_account_id'     => null,
                'verified'              => 0,
                'invited_by_id'         => null,
                'about_me'              => null,
                'bp_type'               => null,
                'bp_business_name'      => null,
                'bp_team_size'          => null,
                'bp_hourly_rate_cents'  => null,
                'bp_categories'         => null,
                'two_factor_enabled'    => 0,
                'w9_status'             => null,
                'locked_at'             => null,
                'locked_reason'         => null,
                'failed_login_count'    => 0,
                'deactivated_at'        => null,
                'last_login_at'         => null,
            ], $user);

            DB::table('users')->updateOrInsert(['id' => $user['id']], $user);
        }

        // user_roles — seed one row per user matching their role enum
        // Must run after users table is populated (FK: user_roles.user_id → users.id)
        $now = now()->toDateTimeString();
        $userRoles = [
            ['user_id' => 'p_sarah',       'role' => 'practitioner'],
            ['user_id' => 'p_rehan',       'role' => 'practitioner'],
            ['user_id' => 'p_david',        'role' => 'practitioner'],
            ['user_id' => 'p_maria',        'role' => 'practitioner'],
            ['user_id' => 'p_access_only',  'role' => 'practitioner'],
            ['user_id' => 'p_locked',       'role' => 'practitioner'],
            ['user_id' => 'p_deactivated',  'role' => 'practitioner'],
            ['user_id' => 'cs_marcus',      'role' => 'continuity_steward'],
            ['user_id' => 'cs_priya',       'role' => 'continuity_steward'],
            ['user_id' => 'cs_alternate',   'role' => 'continuity_steward'],
            ['user_id' => 'cs_resigned',    'role' => 'continuity_steward'],
            ['user_id' => 'ss_linda',       'role' => 'support_steward'],
            ['user_id' => 'ss_james',       'role' => 'support_steward'],
            ['user_id' => 'bp_acme',        'role' => 'business_partner'],
            ['user_id' => 'bp_jamal',       'role' => 'business_partner'],
            ['user_id' => 'bp_team_owner',  'role' => 'business_partner'],
            ['user_id' => 'bp_team_member', 'role' => 'business_partner'],
            ['user_id' => 'admin_root',     'role' => 'admin'],
        ];

        foreach ($userRoles as $ur) {
            DB::table('user_roles')->updateOrInsert(
                ['user_id' => $ur['user_id'], 'role' => $ur['role']],
                ['id' => (string) \Illuminate\Support\Str::uuid(), 'user_id' => $ur['user_id'], 'role' => $ur['role'], 'is_default' => 1, 'enabled_at' => $now]
            );
        }

        // user_preferences — one row per user (UQ on user_id)
        // Schema defaults apply for theme/font_size/language/etc; only user_id is required
        foreach ($userRoles as $ur) {
            DB::table('user_preferences')->updateOrInsert(
                ['user_id' => $ur['user_id']],
                [
                    'id'         => (string) \Illuminate\Support\Str::uuid(),
                    'user_id'    => $ur['user_id'],
                    'theme'      => 'gold',
                    'font_size'  => 100,
                    'compact'    => 0,
                    'language'   => 'en',
                    'timezone'   => 'America/New_York',
                    'date_format'=> 'MM/DD/YYYY',
                    'time_format'=> '12h',
                    'currency'   => 'USD',
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
