<?php

declare(strict_types=1);

namespace App\Services;

use App\Enums\ActivitySeverity;
use App\Enums\InvoiceStatus;
use App\Enums\PayoutStatus;
use App\Enums\PractitionerPaymentKind;
use App\Enums\PractitionerPaymentStatus;
use App\Events\Cs\CsInvoiceAutoGenerated;
use App\Events\Incident\IncidentActivated;
use App\Events\Incident\IncidentAutoClosed;
use App\Events\Incident\IncidentClosed;
use App\Events\Incident\IncidentClosureVerified;
use App\Events\Incident\IncidentEscalated;
use App\Events\Incident\IncidentReadyForClosure;
use App\Events\Incident\IncidentReported;
use App\Events\Incident\IncidentVerified;
use App\Events\Incident\VaultUnsealed;
use App\Jobs\ActivityFanoutJob;
use App\Jobs\IncidentNotificationJob;
use App\Models\ContinuityPlan;
use App\Models\CriticalIncident;
use App\Models\CsInvoice;
use App\Models\CsPayout;
use App\Models\IncidentTask;
use App\Models\PlanSteward;
use App\Models\PlanTask;
use App\Models\PractitionerPayment;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

class IncidentService
{
    public function __construct(private ActivityService $activity) {}

    /**
     * SS reports a critical incident. Bypasses notify_* prefs.
     */
    public function report(ContinuityPlan $plan, User $reporter, array $data): CriticalIncident
    {
        if ($reporter->role !== 'support_steward' && $reporter->id !== $plan->practitioner_id) {
            throw new RuntimeException('Only the practitioner or an assigned Support Steward can report.');
        }

        $incident = CriticalIncident::create([
            'id'                => 'ci_' . Str::lower(Str::random(12)),
            'practitioner_id'   => $plan->practitioner_id,
            'plan_id'           => $plan->id,
            'incident_type'     => $data['incident_type'],
            'reported_by_id'    => $reporter->id,
            'reported_at'       => now(),
            'summary'           => $data['narrative'] ?? null,
            'status'            => 'reported',
        ]);

        // Actor log
        $this->activity->log(
            $reporter->id, $reporter->role?->value === 'support_steward' ? 'support_steward' : 'provider',
            'incident', ActivitySeverity::Critical,
            'incident_reported', 'Critical incident reported',
            "You reported a critical incident: {$data['incident_type']}.",
            CriticalIncident::class, $incident->id, $plan->practitioner_id, 'log', $reporter->id,
        );

        event(new IncidentReported($incident));

        // UNGATED notification — bypasses notify_* prefs
        IncidentNotificationJob::dispatch($incident->id, 'reported');

        return $incident;
    }

    /**
     * CS verifies the report.
     */
    public function verify(CriticalIncident $incident, User $cs, array $data): CriticalIncident
    {
        $isAssignedCs = PlanSteward::where('plan_id', $incident->plan_id)
            ->where('steward_id', $cs->id)
            ->where('steward_type', 'continuity_steward')
            ->where('status', 'active')
            ->exists();
        if (!$isAssignedCs) {
            throw new RuntimeException('Only an assigned Continuity Steward can verify.');
        }

        $incident->update([
            'verified_by_id'     => $cs->id,
            'verified_at'        => now(),
        ]);

        $this->activity->log(
            $cs->id, 'continuity_steward',
            'incident', ActivitySeverity::Critical,
            'incident_verified', 'Critical incident verified',
            "You verified the critical incident.",
            CriticalIncident::class, $incident->id, $incident->practitioner_id, 'log', $cs->id,
        );

        event(new IncidentVerified($incident->fresh()));
        IncidentNotificationJob::dispatch($incident->id, 'verified');

        return $incident->fresh();
    }

    /**
     * Activate the incident. Generates incident_tasks, unseals vault,
     * fans out to ALL stewards via queued job.
     */
    public function activate(CriticalIncident $incident): CriticalIncident
    {
        if ($incident->status === 'active') {
            return $incident;
        }
        if (!$incident->verified_at) {
            throw new RuntimeException('Incident must be verified before activation.');
        }

        DB::transaction(function () use ($incident) {
            $incident->update(['status' => 'active']);

            // Generate incident_tasks from plan_tasks for this incident type
            $planTasks = PlanTask::where('plan_id', $incident->plan_id)
                ->where('incident_type', $incident->incident_type)
                ->orderBy('sort_order')
                ->get();

            foreach ($planTasks as $pt) {
                // Resolve assigned user: first active steward of matching type
                $assignee = PlanSteward::where('plan_id', $incident->plan_id)
                    ->where('steward_type', $pt->assigned_to)
                    ->where('status', 'active')
                    ->orderBy('role') // primary first
                    ->first();
                if (!$assignee) continue;

                IncidentTask::create([
                    'id'                  => 'it_' . Str::lower(Str::random(12)),
                    'incident_id'         => $incident->id,
                    'plan_task_id'        => $pt->id,
                    'title'               => $pt->title,
                    'assigned_to_user_id' => $assignee->steward_id,
                    'status'              => 'pending',
                    'task_list_type'      => $pt->assigned_to,
                ]);
            }
        });

        $plan = ContinuityPlan::find($incident->plan_id);
        event(new IncidentActivated($incident->fresh()));
        event(new VaultUnsealed($plan, $incident->fresh()));

        // Heavy fan-out via queued Job
        $recipients = $this->activity->getPlanStewardRecipients($incident->plan_id);
        $recipients[] = ['user_id' => $plan->practitioner_id, 'portal' => 'provider'];

        ActivityFanoutJob::dispatch($recipients, [
            'module'          => 'incident',
            'severity'        => ActivitySeverity::Critical->value,
            'event_type'      => 'incident_activated',
            'title'           => 'Critical incident activated',
            'description'     => 'A verified critical incident has been activated. Vault access is now available to assigned stewards.',
            'linkable_type'   => 'critical_incident',
            'linkable_id'     => $incident->id,
            'related_user_id' => $incident->verified_by_id,
        ]);

        IncidentNotificationJob::dispatch($incident->id, 'activated');

        return $incident->fresh();
    }

    public function addUpdate(CriticalIncident $incident, User $author, string $body): void
    {
        $this->activity->fanOut(
            $this->activity->getPlanStewardRecipients($incident->plan_id),
            [
                'module'          => 'incident',
                'severity'        => ActivitySeverity::Info,
                'event_type'      => 'incident_update',
                'title'           => "{$author->display_name} posted an incident update",
                'description'     => Str::limit($body, 140),
                'linkable_type'   => 'critical_incident',
                'linkable_id'     => $incident->id,
                'related_user_id' => $author->id,
            ]
        );
    }

    public function close(CriticalIncident $incident, User $closer, string $summary): CriticalIncident
    {
        $incident->update([
            'status'             => 'closed',
            'closed_at'          => now(),
            'summary'            => $summary,
        ]);

        $this->activity->log(
            $closer->id, $closer->role?->value === 'continuity_steward' ? 'continuity_steward' : 'provider',
            'incident', ActivitySeverity::Info,
            'incident_closed', 'Critical incident closed',
            "You closed the critical incident.",
            CriticalIncident::class, $incident->id, $incident->practitioner_id, 'log', $closer->id,
        );

        event(new IncidentClosed($incident->fresh()));

        // Re-seal vault & fan out
        $recipients = $this->activity->getPlanStewardRecipients($incident->plan_id);
        $recipients[] = ['user_id' => $incident->practitioner_id, 'portal' => 'provider'];
        $this->activity->fanOut($recipients, [
            'module'          => 'incident',
            'severity'        => ActivitySeverity::Info,
            'event_type'      => 'incident_closed',
            'title'           => 'Critical incident closed',
            'description'     => Str::limit($summary, 140),
            'linkable_type'   => 'critical_incident',
            'linkable_id'     => $incident->id,
            'related_user_id' => $closer->id,
        ]);

        return $incident->fresh();
    }

    public function escalate(CriticalIncident $incident, string $reason): CriticalIncident
    {
        event(new IncidentEscalated($incident, $reason));

        $recipients = $this->activity->getPlanStewardRecipients($incident->plan_id);
        $this->activity->fanOut($recipients, [
            'module'          => 'incident',
            'severity'        => ActivitySeverity::Critical,
            'event_type'      => 'incident_escalated',
            'title'           => 'Critical incident escalated',
            'description'     => $reason,
            'linkable_type'   => 'critical_incident',
            'linkable_id'     => $incident->id,
        ]);

        return $incident;
    }

    public function getActive(): Collection
    {
        return CriticalIncident::where('status', 'active')->get();
    }

    public function getForPractitioner(string $practitionerId): Collection
    {
        return CriticalIncident::where('practitioner_id', $practitionerId)
            ->orderByDesc('reported_at')
            ->get();
    }

    public function hasActiveForPlan(string $planId): bool
    {
        return CriticalIncident::where('plan_id', $planId)
            ->where('status', 'active')
            ->exists();
    }

    // ─────────────────────────────────────────────────────────────────
    // CS Engagement Contract flow — Rev 2 (§0.7 of continuity plan doc)
    // ─────────────────────────────────────────────────────────────────

    /**
     * Mark a single incident task complete. Called by the CS as they
     * work through the incident's task list. Fires IncidentReadyForClosure
     * the moment the LAST task transitions to complete.
     */
    public function completeTask(IncidentTask $task, User $cs): IncidentTask
    {
        if ($task->assigned_role !== 'continuity_steward') {
            throw new RuntimeException('Only tasks assigned to the Continuity Steward can be completed by CS.');
        }
        if ($task->assigned_to_id !== $cs->id) {
            throw new RuntimeException('You are not the assigned CS for this task.');
        }
        if ((string) $task->status === 'complete') {
            return $task; // idempotent
        }

        $task->update([
            'status'       => 'complete',
            'completed_at' => now(),
        ]);

        $incident = CriticalIncident::find($task->incident_id);
        if ($incident) {
            $this->maybeReadyForClosure($incident);
        }

        return $task->fresh();
    }

    /**
     * Check whether every CS task on this incident is now complete.
     * If yes, and the incident hasn't already fired the "ready for
     * closure" beat, fire it now. Idempotent.
     */
    public function maybeReadyForClosure(CriticalIncident $incident): bool
    {
        if ((string) $incident->status !== 'active') {
            return false;
        }

        $csTasks = IncidentTask::where('incident_id', $incident->id)
            ->where('assigned_role', 'continuity_steward')
            ->get();

        if ($csTasks->isEmpty()) {
            return false;
        }

        $allComplete = $csTasks->every(fn ($t) => (string) $t->status === 'complete');
        if (!$allComplete) {
            return false;
        }

        // Idempotency guard: only fire once. Uses a marker on the incident's
        // summary field to avoid schema changes — full solution should add
        // a dedicated `ready_for_closure_at` column later.
        if ($incident->closed_at || str_contains((string) ($incident->summary ?? ''), '[READY_FOR_CLOSURE]')) {
            return false;
        }

        $incident->update([
            'summary' => trim(($incident->summary ?? '') . "\n[READY_FOR_CLOSURE]" . now()->toIso8601String()),
        ]);

        event(new IncidentReadyForClosure($incident->fresh()));

        // Notify Provider + all Support Stewards
        $this->activity->log(
            $incident->practitioner_id, 'provider', 'incident',
            ActivitySeverity::Warning,
            'incident_ready_for_closure',
            'All continuity tasks are complete',
            'Your Continuity Steward has completed every incident task. Please verify closure so payment can be finalised.',
            CriticalIncident::class, $incident->id, null, 'notification', null,
        );

        $ssStewards = PlanSteward::where('plan_id', $incident->plan_id)
            ->where('steward_type', 'support_steward')
            ->where('status', 'active')
            ->pluck('steward_id');

        foreach ($ssStewards as $ssId) {
            $this->activity->log(
                $ssId, 'support_steward', 'incident',
                ActivitySeverity::Warning,
                'incident_ready_for_closure',
                'Verification requested',
                'The Continuity Steward has completed all tasks. You can verify closure if the practitioner is unavailable.',
                CriticalIncident::class, $incident->id, null, 'notification', null,
            );
        }

        return true;
    }

    /**
     * Provider or Support Steward explicitly verifies that the CS's
     * closure of the incident is acceptable. Sets verified_by_id and
     * fires IncidentClosureVerified. Does NOT close the incident by
     * itself — the CS still calls closeWithInvoice() after verification.
     */
    public function verifyClosure(CriticalIncident $incident, User $verifier, string $role): CriticalIncident
    {
        if (!in_array($role, ['provider', 'support_steward', 'system_auto'], true)) {
            throw new RuntimeException('Invalid verifier role.');
        }

        // Guard: Provider must be the plan owner; SS must be active on the plan
        if ($role === 'provider' && $verifier->id !== $incident->practitioner_id) {
            throw new RuntimeException('Only the practitioner can verify as provider.');
        }
        if ($role === 'support_steward') {
            $isSs = PlanSteward::where('plan_id', $incident->plan_id)
                ->where('steward_id', $verifier->id)
                ->where('steward_type', 'support_steward')
                ->where('status', 'active')
                ->exists();
            if (!$isSs) {
                throw new RuntimeException('You are not an active Support Steward for this plan.');
            }
        }

        $incident->update([
            'verified_by_id' => $verifier->id,
            'verified_at'    => $incident->verified_at ?? now(), // preserve original CS verification of the incident itself
        ]);

        event(new IncidentClosureVerified($incident->fresh(), $verifier, $role));

        $this->activity->log(
            $incident->practitioner_id, 'provider', 'incident',
            ActivitySeverity::Info,
            'incident_closure_verified',
            'Incident closure verified',
            "Closure verified by {$role}. The Continuity Steward may now finalize.",
            CriticalIncident::class, $incident->id, $verifier->id, 'log', $verifier->id,
        );

        return $incident->fresh();
    }

    /**
     * CS-initiated close that atomically:
     *   1. closes the incident (re-seals vault, fans out)
     *   2. if the CS's plan_steward.fee_cents > 0, auto-generates a CsInvoice
     *   3. if plan_steward.auto_charge = 1 AND Provider has a default PM
     *      AND CS has stripe_connected, immediately fires the destination charge
     *
     * The CS calls this method after receiving verification (or the system
     * auto-verified after 7 days).
     */
    public function closeWithInvoice(
        CriticalIncident $incident,
        User $cs,
        string $summary,
        ?PayoutService $payouts = null
    ): CriticalIncident {
        // Close the incident first via the existing pathway
        $closed = $this->close($incident, $cs, $summary);

        // Resolve the CS engagement for this incident
        $engagement = PlanSteward::where('plan_id', $closed->plan_id)
            ->where('steward_id', $cs->id)
            ->where('steward_type', 'continuity_steward')
            ->where('status', 'active')
            ->first();

        if (!$engagement || !$engagement->isPaidEngagement()) {
            return $closed;
        }

        // Auto-generate the invoice
        $invoice = CsInvoice::create([
            'id'              => (string) Str::uuid(),
            'cs_id'           => $cs->id,
            'practitioner_id' => $closed->practitioner_id,
            'invoice_number'  => 'CS-AUTO-' . strtoupper(Str::random(6)),
            'status'          => InvoiceStatus::Sent->value, // straight to sent — no draft step
            'total_cents'     => (int) $engagement->fee_cents,
            'currency'        => 'USD',
            'issued_at'       => now(),
        ]);

        $autoCharged = false;
        $provider    = User::find($closed->practitioner_id);

        // Attempt auto-charge if the engagement is configured for it
        $canAutoCharge = $engagement->auto_charge
            && $engagement->payment_terms === 'on_close'
            && $payouts
            && $provider
            && $provider->stripe_id
            && $provider->stripe_payment_method_id
            && $cs->stripe_account_id;

        if ($canAutoCharge) {
            try {
                $result = $payouts->chargeProviderToCs(
                    provider:    $provider,
                    cs:          $cs,
                    amountCents: (int) $engagement->fee_cents,
                    meta:        ['cs_invoice_id' => $invoice->id, 'incident_id' => $closed->id, 'auto_charged' => true],
                    description: 'CS engagement auto-charge — incident ' . $closed->id,
                );

                $invoice->update([
                    'status'                   => $result['status'] === 'paid' ? InvoiceStatus::Paid->value : InvoiceStatus::Sent->value,
                    'stripe_payment_intent_id' => $result['stripe_payment_intent_id'],
                    'stripe_transfer_id'       => $result['stripe_transfer_id'] ?? null,
                    'paid_at'                  => $result['status'] === 'paid' ? now() : null,
                ]);

                if ($result['status'] === 'paid') {
                    $autoCharged = true;
                    // Provider spend history
                    PractitionerPayment::create([
                        'id'                   => (string) Str::uuid(),
                        'practitioner_id'      => $provider->id,
                        'kind'                 => PractitionerPaymentKind::CsFee->value,
                        'amount_cents'         => (int) $engagement->fee_cents,
                        'currency'             => 'USD',
                        'status'               => PractitionerPaymentStatus::Paid->value,
                        'payment_method_label' => 'CS Engagement Auto-Charge — ' . $invoice->invoice_number,
                        'stripe_charge_id'     => $result['stripe_payment_intent_id'],
                        'stripe_transfer_id'   => $result['stripe_transfer_id'] ?? null,
                        'paid_at'              => now(),
                    ]);
                    // CS payout history
                    CsPayout::create([
                        'id'                => (string) Str::uuid(),
                        'cs_id'             => $cs->id,
                        'amount_cents'      => (int) $engagement->fee_cents,
                        'currency'          => 'USD',
                        'status'            => PayoutStatus::Paid->value,
                        'description'       => 'Auto-charge for ' . $invoice->invoice_number,
                        'stripe_payout_id'  => $result['stripe_transfer_id'] ?? $result['stripe_payment_intent_id'],
                        'paid_at'           => now(),
                    ]);
                }
            } catch (\Throwable $e) {
                // Auto-charge failure isn't fatal — invoice remains "sent" and
                // Provider will need to pay it manually via Finances.
                Log::warning('[CS_ENGAGEMENT] auto-charge failed', [
                    'incident_id' => $closed->id,
                    'invoice_id'  => $invoice->id,
                    'error'       => $e->getMessage(),
                ]);
            }
        }

        event(new CsInvoiceAutoGenerated($invoice->fresh(), $closed->id, $autoCharged));

        $this->activity->log(
            $provider?->id ?? $closed->practitioner_id, 'provider', 'finances',
            ActivitySeverity::Info,
            $autoCharged ? 'cs_engagement_auto_charged' : 'cs_engagement_invoice_generated',
            $autoCharged ? 'CS engagement fee auto-charged' : 'CS engagement invoice generated',
            $autoCharged
                ? 'The pre-agreed CS fee of $' . number_format($engagement->fee_cents / 100, 2) . ' has been charged.'
                : 'A CS engagement invoice for $' . number_format($engagement->fee_cents / 100, 2) . ' has been sent. Pay it from Finances.',
            CsInvoice::class, $invoice->id, $cs->id, 'log', $cs->id,
        );

        return $closed;
    }

    /**
     * System auto-close path — invoked by IncidentAutoCloseCheckJob when
     * an incident sits in "ready for closure" state past the configured
     * window with no explicit verification.
     */
    public function autoClose(CriticalIncident $incident, int $windowDays, ?PayoutService $payouts = null): void
    {
        // Synthetic verifier — the system itself
        $systemUser = User::where('role', 'admin')->orderBy('created_at')->first();
        if (!$systemUser) {
            Log::warning('[AUTO_CLOSE] no admin user to act as system verifier', ['incident' => $incident->id]);
            return;
        }

        $this->verifyClosure($incident, $systemUser, 'system_auto');

        // Find the CS engagement to close on their behalf
        $csSteward = PlanSteward::where('plan_id', $incident->plan_id)
            ->where('steward_type', 'continuity_steward')
            ->where('status', 'active')
            ->first();

        $cs = $csSteward ? User::find($csSteward->steward_id) : null;
        if (!$cs) {
            Log::warning('[AUTO_CLOSE] no active CS to close for', ['incident' => $incident->id]);
            return;
        }

        $summary = "Auto-closed after {$windowDays} days without explicit verification from Provider or Support Steward.";
        $this->closeWithInvoice($incident, $cs, $summary, $payouts);

        event(new IncidentAutoClosed($incident->fresh(), $windowDays));
    }
}
