<?php

declare(strict_types=1);

namespace App\Events\Cs;

use App\Models\CsInvoice;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

/**
 * Fired when IncidentService::closeWithInvoice() auto-creates a CS
 * invoice for a paid engagement. Distinct from a CS manually issuing
 * one via /continuity-steward/invoices. Triggers the "invoice
 * automatically generated on incident close" email to the Provider.
 */
class CsInvoiceAutoGenerated
{
    use Dispatchable, SerializesModels;

    public function __construct(
        public CsInvoice $invoice,
        public string $incidentId,
        public bool $autoCharged
    ) {}
}
